use_frameworks!

platform :ios, '11.0'

target 'SettingStorageKit_Example' do
  pod 'SettingStorageKit', :path => '../'

  target 'SettingStorageKit_Tests' do
    inherit! :search_paths

    
  end
end
